model_name_or_path: "D:/3dlib/LLM/Qwen3-1.7B"
train_data_path: "D:/cjq/project/python/qwen3_Lora_sft_project/data/tokenized/train"
eval_data_path: "D:/cjq/project/python/qwen3_Lora_sft_project/data/tokenized/eval"
output_dir: "log/medicalQA_sft"
# === 数据处理 ===
max_seq_length: 2048
# === 优化器与学习率 ===
learning_rate: 2e-5
lr_scheduler_type: "cosine"
warmup_ratio: 0.03
weight_decay: 0.01
# === 训练参数 ===
num_train_epochs: 3
per_device_train_batch_size: 1
per_device_eval_batch_size: 1
gradient_accumulation_steps: 16
gradient_checkpointing: true
fp16: true
# === 日志与保存 ===
logging_steps: 10
save_steps: 500
eval_steps: 500
save_strategy: "epoch"
evaluation_strategy: "epoch"
report_to: [ "tensorboard" ]
logging_dir: "log/tensorboard"
save_total_limit: 2
load_best_model_at_end: true
metric_for_best_model: "eval_loss"
greater_is_better: false